### ISSUE TITLE
Add support of bulk operations with fulfillment center

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-inventory#12]
Allow to Get or Update multiple fulfillment centers by one time

**Comment by yecli** [comment]
Please handle review comments: https://github.com/VirtoCommerce/vc-module-inventory/pull/17

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-module-inventory/releases/tag/v2.13.7
