### ISSUE TITLE
Fulfillment center list & details blades have duplicates in Core module

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-inventory#20]
And details blade in Inventory module have a bug: there is no input for Line 2 of fulfillment center address.

Core module blades:
![image](https://user-images.githubusercontent.com/6369252/50701800-bcb6f800-1070-11e9-90d5-61f93a58e6ab.png)
Inventory module blades:
![image](https://user-images.githubusercontent.com/6369252/50701861-e40dc500-1070-11e9-9021-da9dd3892715.png)

**Comment by tatarincev** [comment]
This is the old version, when the functionality of the Fulfillment Center was part of the Core module and is left for backwards compatibility. Now this code is outdated and will be removed in future releases.
Thanks for pointed for this.

**Comment by tatarincev** [comment]
I guess we nothing to do with this issue. Because of the platform  3.0 version doesn't contain this duplication.
