### ISSUE TITLE
FulfillmentCenterEntity can not be extended with one-to-many and many-to-many relations

### ISSUE THREAD

**Issue by avas** [VirtoCommerce/vc-module-inventory#28]
In Heineken Nigeria project, we needed to add support for business sectors and sections for fulfillment centers - basically, a couple of additional many-to-many relations (one fulfillment center can belong to many business sectors and many sections). We did it by extending the `FulfillmentCenterEntity` with the following code:
```csharp
public class HngFulfillmentCenterEntity : FulfillmentCenterEntity
{
    public HngFulfillmentCenterEntity()
    {
        Sectors = new NullCollection<HngFulfillmentCenterSectorEntity>();
        Sections = new NullCollection<HngFulfillmentCenterSectionEntity>();
    }

    public ObservableCollection<HngFulfillmentCenterSectorEntity> Sectors { get; set; }
    public ObservableCollection<HngFulfillmentCenterSectionEntity> Sections { get; set; }

    // ...
    
    public override void Patch(FulfillmentCenterEntity target)
    {
        base.Patch(target);

        if (target is HngFulfillmentCenterEntity hngFulfillmentCenterEntity)
        {
            // ...

            if (!Sectors.IsNullCollection())
            {
                var sectorComparer = AnonymousComparer.Create((HngFulfillmentCenterSectorEntity x) => x.Sector);
                Sectors.Patch(hngFulfillmentCenterEntity.Sectors, sectorComparer, (sourceSector, targetSector) => targetSector.Sector = sourceSector.Sector);
            }

            if (!Sections.IsNullCollection())
            {
                var sectionComparer = AnonymousComparer.Create((HngFulfillmentCenterSectionEntity x) => x.Section);
                Sections.Patch(hngFulfillmentCenterEntity.Sections, sectionComparer, (sourceSection, targetSection) => targetSection.Section = sourceSection.Section);
            }
        }
    }
}

public class HngFulfillmentCenterSectorEntity : Entity
{
    // ...

    #region Navigation Properties
    public string HngFulfillmentCenterId { get; set; }
    public virtual HngFulfillmentCenterEntity HngFulfillmentCenter { get; set; }
    #endregion
}

public class HngFulfillmentCenterSectionEntity : Entity
{
    // ...

    #region Navigation Properties
    public string HngFulfillmentCenterId { get; set; }
    public virtual HngFulfillmentCenterEntity HngFulfillmentCenter { get; set; }
    #endregion
}
```

`HngFulfillmentCenterId` column is a non-nullable FK with cascade deletion for both `HngFulfillmentCenterSectorEntity` and `HngFulfillmentCenterSectionEntity`.

This code works well when adding new FFC-to-sector and FFC-to-section relations, but fails with the following error when attempting to remove relations:
```
Cannot insert the value NULL into column 'HngFulfillmentCenterId', table 'hng-dev.dbo.HngFulfillmentCenterSection'; column does not allow nulls. INSERT fails. The statement has been terminated.
```

Here is the reason of this error:
1. We attempt to save changed fulfillment center (with removed sections or sectors) using `FulfillmentCenterService.SaveChanges()` method.
2. It detects that the fulfillment center being saved already exists in database and attempts to patch existing entity.
3. `HngFulfillmentCenterEntity.Patch()` method patches `Sections` and `Sectors`, and it removes items that were removed from these collections.
4. When applying unit of work, EF detects that sectors and/or sections were removed from the `HngFulfillmentCenterEntity.Sections` or `HngFulfillmentCenterEntity.Sectors` collections, but it does not know what to do with it. So, instead of removing that entity from the database, it attempts to just break the reference by setting `HngFulfillmentCenterId` to `null`, but fails to do so because this field is non-nullable. That's what causes the error.

Many other modules for VC platform use the `ObservableChangesTracker` for tracking creation/removal of one-to-many and many-to-many relations and add/remove these relations to the database - for example, `VirtoCommerce.Cart` module [does it](https://github.com/VirtoCommerce/vc-module-cart/blob/9c5ffc2885328ee84e1b1c7f8f14a24019e71e99/VirtoCommerce.CartModule.Data/Services/ShoppingCartServiceImpl.cs#L69-L87) for tracking line items, coupons and many other entities related to the cart. But, unfortunately, `FulfillmentCenterService` does not use it when saving fulfillment centers, and it can't be easily derived to use changes tracker. So, it would be nice if it just used changes tracker to track fulfillment center dependencies.

**Comment by yecli** [comment]
Released in [v2.13.5](https://github.com/VirtoCommerce/vc-module-inventory/releases/tag/v2.13.5).
