### ISSUE TITLE
Allow extension of search query in FulfillmentCenterSearchService

### ISSUE THREAD

**Issue by avas** [VirtoCommerce/vc-module-inventory#34]
**Description**
Current implementation of `FulfillmentCenterSearchService` does not allow to extend the FFC search criteria with some new properties and allow to search for these properties without massive copy-pasting of the code, because:
* Database query is built inside of the `Search()` method, so it can't be simply overridden;
* And furthermore, the `Search()` method is not virtual.

So, I think it would be nice if `Search()` method was virtual, and search query building was done in a separate virtual method (as it is done in search services in other modules).

**Additional context**
In HOT, we extend fulfillment centers with some additional fields that define the business area of the FFC. When searching for applicable FFCs, we want to filter values of these fields on database side. So, general steps would be like these:
1. Extend `FulfillmentCenterSearchCriteria` by adding additional fields and override it in `AbstractTypeFactory`;
2. Extend `FulfillmentCenterSearchService` and add fields of extended search criteria to the FFC query.

But, as said before, `Search()` method is not virtual, and the query is built in that method itself. So to extend the FFC search code, we'll have to copy-paste the code of `FulfillmentCenterSearchService` to a separate class and add some custom logic to that copy. Would be very handy if it wasn't necessary.

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-module-inventory/releases/tag/v2.13.7
