### ISSUE TITLE
Limit widget columns count on fulfillment center details blade

### ISSUE THREAD

**Issue by avas** [VirtoCommerce/vc-module-inventory#36]
Currently, we only limit width of widget container on fulfillment center details blade. but do not limit count of widget columns. This causes problems when adding new widgets to the blade - if there are already 3 columns of widgets and we want to add new 1x1 widget, then it will appear out of widget boundaries:
![image](https://user-images.githubusercontent.com/1835759/65676044-6a43be80-e079-11e9-8cca-db4b6c5c68f4.png)
So, my proposal is to allow only 3 columns of widgets on this blade.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-inventory/releases/tag/v2.13.6
