### ISSUE TITLE
api/inventory/products doesn't working

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-inventory#5]
Return a false data
api/inventory/products/{productId} works well

**Comment by eMazeika** [comment]
a more detailed description needed

**Comment by asvishnyakov** [comment]
I think already was fixed by @tatarincev

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
